import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="flex flex-row text-xl justify-between mx-8 py-4">
					<h2>next auth course</h2>
					<nav className="flex flex-row gap-4">
						<Link href={"/login"}>Login</Link>
						<Link href={"/signup"}>Signup</Link>
					</nav>
				</header>
				<Toaster />
				<main className="flex flex-col justify-center items-center ">
					{children}
				</main>
			</body>
		</html>
	);
}
